export const allRiders = [
    { img: 'rider1.jpg', title: 'Rider 1' },
    { img: 'rider2.jpg', title: 'Rider 2' },
    { img: 'rider3.jpg', title: 'Rider 3' },
    { img: 'rider4.jpg', title: 'Rider 4' },
    { img: 'rider5.jpg', title: 'Rider 5' },
    { img: 'rider6.jpg', title: 'Rider 6' },
    { img: 'rider7.jpg', title: 'Rider 7' },
    { img: 'rider8.jpg', title: 'Rider 8' },
    { img: 'rider9.jpg', title: 'Rider 9' },
    { img: 'rider10.jpg', title: 'Rider 10' },
    { img: 'rider11.jpg', title: 'Rider 1' },
    { img: 'rider12.jpg', title: 'Rider 12' },
    { img: 'rider13.jpg', title: 'Rider 13' },
    { img: 'rider14.jpg', title: 'Rider 14' },
    { img: 'rider15.jpg', title: 'Rider 15' },
    { img: 'rider16.jpg', title: 'Rider 16' },
    { img: 'rider17.jpg', title: 'Rider 17' },
    { img: 'rider18.jpg', title: 'Rider 18' },
    { img: 'rider19.jpg', title: 'Rider 19' },
    { img: 'rider20.jpg', title: 'Rider 20' },
  ];
  